apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ucpe-poc-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://srinath-koneru.github.io/uCPE-helm-repo/
