apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-kubevirt
spec:
  releaseName: test-kubevirt
  chart:
    spec:
      chart: testvmi-nocloud
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: ucpe-poc-charts
        namespace: flux-system
      interval: 1m0s
  interval: 1m0s
